### ISSUE TITLE
panicでました

### ISSUE THREAD

**Issue by sinohiro** [ITNS-LAB/gtfs-gorm#7]
`
sinohiro@DESKTOP-CFB0EP4:~/git/gtfs-gorm$ ./gtfsdb-go --file ./gtfs-kitami_unv-jp_shiga_koka_city.zip --dsn postgres://hoge:hoge@localhost:5432/hoge --recal --shapesex --shapesdetail --geom
          __  ____         ____                    
   ____ _/ /_/ __/________/ / /_        ____ _____ 
  / __ `/ __/ /_/ ___/ __  / __ \______/ __ `/ __ \
 / /_/ / /_/ __(__  ) /_/ / /_/ /_____/ /_/ / /_/ /
 \__, /\__/_/ /____/\__,_/_.___/      \__, /\____/ 
/____/                               /____/

15:40:12.290 INFO [gtfs_schedule.go:75] agency.txt の挿入が完了しました。 
15:40:12.292 INFO [gtfs_schedule.go:75] calendar.txt の挿入が完了しました。 
15:40:12.316 INFO [gtfs_schedule.go:75] calendar_dates.txt の挿入が完了しました。 
15:40:12.323 INFO [gtfs_schedule.go:75] routes.txt の挿入が完了しました。 
15:40:12.351 INFO [gtfs_schedule.go:75] stops.txt の挿入が完了しました。 
15:40:13.334 INFO [gtfs_schedule.go:75] shapes.txt の挿入が完了しました。 
15:40:13.344 INFO [gtfs_schedule.go:75] trips.txt の挿入が完了しました。 
15:40:13.522 INFO [gtfs_schedule.go:75] stop_times.txt の挿入が完了しました。 
15:40:13.524 INFO [gtfs_schedule.go:75] transfers.txt の挿入が完了しました。 
15:40:13.524 WARN [gtfs_schedule.go:67] frequencies.txtの読み込みができませんでした。ファイルが存在しない可能性があります。 error=open tmp/gtfs-kitami_unv-jp_shiga_koka_city/frequencies.txt: no such file or directory path="tmp/gtfs-kitami_unv-jp_shiga_koka_city/frequencies.txt" 
15:40:13.526 INFO [gtfs_schedule.go:75] fare_attributes.txt の挿入が完了しました。 
15:40:13.874 INFO [gtfs_schedule.go:75] fare_rules.txt の挿入が完了しました。 
15:40:13.874 WARN [gtfs_schedule.go:67] pathways.txtの読み込みができませんでした。ファイルが存在しない可能性があります。 error=open tmp/gtfs-kitami_unv-jp_shiga_koka_city/pathways.txt: no such file or directory path="tmp/gtfs-kitami_unv-jp_shiga_koka_city/pathways.txt" 
15:40:13.874 WARN [gtfs_schedule.go:67] levels.txtの読み込みができませんでした。ファイルが存在しない可能性があります。 error=open tmp/gtfs-kitami_unv-jp_shiga_koka_city/levels.txt: no such file or directory path="tmp/gtfs-kitami_unv-jp_shiga_koka_city/levels.txt" 
15:40:13.876 INFO [gtfs_schedule.go:75] feed_info.txt の挿入が完了しました。 
15:40:13.922 INFO [gtfs_schedule.go:75] translations.txt の挿入が完了しました。 
15:40:13.922 WARN [gtfs_schedule.go:67] attributions.txtの読み込みができませんでした。ファイルが存在しない可能性があります。 error=open tmp/gtfs-kitami_unv-jp_shiga_koka_city/attributions.txt: no such file or directory path="tmp/gtfs-kitami_unv-jp_shiga_koka_city/attributions.txt" 
15:40:13.922 INFO [gtfsdb.go:257] テーブル[trips] tripsテーブルのgeomを更新します。 
15:40:14.734 INFO [gtfsdb.go:292] テーブル[trips] tripsテーブルのgeomを更新が完了しました。 
15:40:14.735 INFO [gtfsdb.go:133] テーブル[shapes] shape_dist_traveled の再計算を行います。 
15:40:15.058 INFO [gtfsdb.go:162] テーブル[shapes] shape_dist_traveled の再計算が完了しました。 
15:40:15.058 INFO [gtfsdb.go:172] テーブル[shapes] shape_dist_traveled の更新を行います。 
15:40:35.405 INFO [gtfsdb.go:177] テーブル[shapes] shape_dist_traveled の更新が完了しました。 
15:40:35.405 INFO [gtfsdb.go:257] テーブル[trips] tripsテーブルのgeomを更新します。 
15:40:36.247 INFO [gtfsdb.go:292] テーブル[trips] tripsテーブルのgeomを更新が完了しました。 

2024/12/18 15:40:36 /home/sinohiro/git/gtfs-gorm/gtfsdb/infrastructure/gtfs_schedule.go:269 SLOW SQL >= 200ms
[529.045ms] [rows:95391] SELECT trips.trip_id, trips.shape_id, shapes.shape_pt_lat, shapes.shape_pt_lon, shapes.shape_pt_sequence, shapes.shape_dist_traveled, NULL AS stop_id, shapes.geom FROM "shapes" join trips on trips.shape_id = shapes.shape_id ORDER BY trips.trip_id,shapes.shape_pt_sequence
15:40:38.117 INFO [gtfsdb.go:191] shapes_exテーブルを作成しました。 
15:40:38.125 INFO [gtfsdb.go:198] stop_timesテーブルshape_dist_traveledの更新を開始しました。 
15:40:38.125 INFO [gtfsdb.go:199] shape_exテーブルstop_idの更新を開始しました。 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ITNS-LAB/gtfs-gorm/gtfsdb/usecase.gtfsDbUseCase.createShapeEx({{0xcaa090?, 0x117fbc0?}, {0xcb25f8?, 0xc00012a498?}}, {{0x0, 0x0}, {0x7ffdb52d61b7, 0x28}, 0x1, 0x1, ...})
        /home/sinohiro/git/gtfs-gorm/gtfsdb/usecase/gtfsdb.go:229 +0x87a
github.com/ITNS-LAB/gtfs-gorm/gtfsdb/usecase.gtfsDbUseCase.GtfsDbFile({{0xcaa090?, 0x117fbc0?}, {0xcb25f8?, 0xc00012a498?}}, {{0x0, 0x0}, {0x7ffdb52d61b7, 0x28}, 0x1, 0x1, ...})
        /home/sinohiro/git/gtfs-gorm/gtfsdb/usecase/gtfsdb.go:118 +0x456
github.com/ITNS-LAB/gtfs-gorm/gtfsdb/interfaces.GtfsDbFile({{0x0, 0x0}, {0x7ffdb52d61b7, 0x28}, 0x1, 0x1, 0x1, 0x1, {0x7ffdb52d61e6, 0x28}, ...})
        /home/sinohiro/git/gtfs-gorm/gtfsdb/interfaces/gtfsdb.go:12 +0xfd
main.main()
        /home/sinohiro/git/gtfs-gorm/cmd/gtfsdb-go/main.go:64 +0x58b
`
        
NASにあるURLから甲賀市のGTFSデータを読み込みdocker で立ち上げたdbにGTFSのデータを流し込む際にpanicが発生してコードがストップします

・pc(M1Mac と研究室PC(i5-12500))の環境変えても同じ問題が発生しました

**Comment by Atsu06** [comment]
存在しないshape_idを参照したことが原因です。
現在別の修正も行っていますので、その修正と並行してバグの修正をおこないます。
